spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  # 파일관리?
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jydb?serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: jaeyoung
    password: 'jaeyoung$#21'
    hikari:
      pool-name: SpringBootHikariCP-pool
      maximum-pool-size: 10
      minimum-idle: 10
      max-lifetime: 2000000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      idle-timeout: 30000

  #  driver-class-name: org.h2.Driver
    # url: jdbc:h2:mem:jydb;DB_CLOSE_DELAY=-1
  #  url: jdbc:h2:file:${user.home}/db/h2/jydb;DB_CLOSE_DELAY=-1
  #  username: sa
  #  password:

  # h2-console
  #h2:
  #  console:
  #    path: /h2-console
  #    enabled: true
  #    settings:
  #      web-allow-others: false

  # jpa 설정
  jpa:
    generate-ddl: true
    show-sql: true
  #  database: h2
  #  database-platform: org.hibernate.dialect.H2Dialect
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

  redis:
    host: localhost
    port: 6379
    database: 0
    ssl: false

  task:
    expiredBiddingPeriod: "0 * * * * *"

logging:
  level:
    root: info
  #config: classpath:log4j2.yml

server:
  port: 9090

springdoc:
  version: '@springdoc.version@'
  api-docs:
    enabled:  true